### ISSUE TITLE
AttributeError: 'Redis' object has no attribute 'client'

### ISSUE THREAD

**Issue by hw201212** [microsoft/qlib#102]
[9268:MainThread](2020-12-12 09:48:29,096) INFO - qlib.Initialization - [__init__.py:42] - default_conf: client.
Traceback (most recent call last):
  File "D:\python\lib\site-packages\pyqlib-0.6.0.dev0-py3.7-win-amd64.egg\qlib\utils\__init__.py", line 604, in can_use_cache
    r.client()
AttributeError: 'Redis' object has no attribute 'client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/code/QuantInvest/invest-core/src/main/python/invest/qlib_apply/qlib_test.py", line 85, in <module>
    qlib.init()
  File "D:\python\lib\site-packages\pyqlib-0.6.0.dev0-py3.7-win-amd64.egg\qlib\__init__.py", line 56, in init
    if not can_use_cache():
  File "D:\python\lib\site-packages\pyqlib-0.6.0.dev0-py3.7-win-amd64.egg\qlib\utils\__init__.py", line 608, in can_use_cache
    r.close()
AttributeError: 'Redis' object has no attribute 'close'

**Comment by hw201212** [comment]
if __name__ == '__main__':
    data_handler_config = {
        "start_time": "2008-01-01",
        "end_time": "2020-08-01",
        "fit_start_time": "2008-01-01",
        "fit_end_time": "2014-12-31",
        "instruments": "csi300",
    }
    qlib.init()
    h = Alpha158(**data_handler_config)
    print(h.get_cols())

**Comment by zhupr** [comment]
@hw201212 Hi
You can try to update redis: `python -m pip install -U redis`

**Comment by hw201212** [comment]
> 
> 
> @hw201212 Hi
> You can try to update redis: `python -m pip install -U redis`

Thanks，it's OK!
