### ISSUE TITLE
NameError: name 'rolling_resi' is not defined

### ISSUE THREAD

**Issue by ArtificialZeng** [microsoft/qlib#1238]
File ~\AppData\Roaming\Python\Python38\site-packages\qlib\data\data.py:917, in LocalDatasetProvider.dataset(self, instruments, fields, start_time, end_time, freq, inst_processors)
    915     start_time = cal[0]
    916     end_time = cal[-1]
--> 917 data = self.dataset_processor(
    918     instruments_d, column_names, start_time, end_time, freq, inst_processors=inst_processors
    919 )
    921 return data

File ~\AppData\Roaming\Python\Python38\site-packages\qlib\data\data.py:572, in DatasetProvider.dataset_processor(instruments_d, column_names, start_time, end_time, freq, inst_processors)
    562     inst_l.append(inst)
    563     task_l.append(
    564         delayed(DatasetProvider.inst_calculator)(
    565             inst, start_time, end_time, freq, normalize_column_names, spans, C, inst_processors
    566         )
    567     )
    569 data = dict(
    570     zip(
    571         inst_l,
--> 572         ParallelExt(n_jobs=workers, backend=C.joblib_backend, maxtasksperchild=C.maxtasksperchild)(task_l),
    573     )
    574 )
    576 new_data = dict()
    577 for inst in sorted(data.keys()):

File H:\A_software\Anaconda3\envs\py386\lib\site-packages\joblib\parallel.py:1056, in Parallel.__call__(self, iterable)
   1053     self._iterating = False
   1055 with self._backend.retrieval_context():
-> 1056     self.retrieve()
   1057 # Make sure that we get a last message telling us we are done
   1058 elapsed_time = time.time() - self._start_time

File H:\A_software\Anaconda3\envs\py386\lib\site-packages\joblib\parallel.py:935, in Parallel.retrieve(self)
    933 try:
    934     if getattr(self._backend, 'supports_timeout', False):
--> 935         self._output.extend(job.get(timeout=self.timeout))
    936     else:
    937         self._output.extend(job.get())

File H:\A_software\Anaconda3\envs\py386\lib\multiprocessing\pool.py:771, in ApplyResult.get(self, timeout)
    769     return self._value
    770 else:
--> 771     raise self._value

NameError: name 'rolling_resi' is not defined

## To Reproduce

1.
1.
1.

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:
 - Python version:
 - OS (`Windows`, `Linux`, `MacOS`):
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by weibo021** [comment]
I'm new to pyqlib and I ran into the same problem yesterday. Could it be that the dataset is causing the problem. When I did the test in workflow_by_code.ipyn, it started reporting these errors again when I mistakenly used the default alpha158, and it worked fine when I changed it to the model's corresponding alpha360.

**Comment by lerit** [comment]
same problem when load data which dump_all from csv file: 
**error:**
```
[27594:MainThread](2022-08-12 00:22:37,104) INFO - qlib.Initialization - [config.py:413] - default_conf: client.
[27594:MainThread](2022-08-12 00:22:37,621) INFO - qlib.Initialization - [__init__.py:74] - qlib successfully initialized based on client settings.
[27594:MainThread](2022-08-12 00:22:37,622) INFO - qlib.Initialization - [__init__.py:76] - data_path={'__DEFAULT_FREQ': PosixPath('/data/home/xxxxx/code/qlib-research/qlib-platform/qlib_data/data')}
[27594:MainThread](2022-08-12 00:22:37,633) ERROR - qlib.data - [data.py:397] - ERROR: field [close] contains invalid operator/variable ['close']
Traceback (most recent call last):
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/qlib/data/data.py", line 1180, in features
    return DatasetD.dataset(
TypeError: dataset() got multiple values for argument 'inst_processors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/qlib/data/data.py", line 394, in get_expression_instance
    expression = eval(parse_field(field))
  File "<string>", line 1, in <module>
NameError: name 'close' is not defined
[27594:MainThread](2022-08-12 00:22:37,635) ERROR - qlib.workflow - [utils.py:41] - An exception has been raised[NameError: name 'close' is not defined].
  File "/data/home/xxxxx/code/qlib-research/qlib-platform/data-loader/index.py", line 35, in <module>
    df=D.features(instruments,base_fields)
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/qlib/data/data.py", line 1184, in features
    return DatasetD.dataset(instruments, fields, start_time, end_time, freq, inst_processors=inst_processors)
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/qlib/data/data.py", line 917, in dataset
    data = self.dataset_processor(
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/qlib/data/data.py", line 572, in dataset_processor
    ParallelExt(n_jobs=workers, backend=C.joblib_backend, maxtasksperchild=C.maxtasksperchild)(task_l),
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/qlib/data/data.py", line 610, in inst_calculator
    obj[field] = ExpressionD.expression(inst, field, start_time, end_time, freq)
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/qlib/data/data.py", line 839, in expression
    expression = self.get_expression_instance(field)
  File "/home/xxxxx/miniconda3/envs/qlib/lib/python3.8/site-packages/qlib/data/data.py", line 394, in get_expression_instance
    expression = eval(parse_field(field))
  File "<string>", line 1, in <module>
NameError: name 'close' is not defined
```

**dump_all:**
```
python ./dump_bin.py dump_all --csv_path xxx --qlib_dir yyy --date_field_name date
```
**load data:**
```
    qlib.init(provider_uri=provider_uri, region=REG_CN)
    df=D.features(instruments,["close"])
```

**env:**
```
Linux
x86_64
Linux-5.10.36-amd64-desktop-x86_64-with-glibc2.17
#2 SMP Mon Apr 26 11:56:35 CST 2021
[000009.csv](https://github.com/microsoft/qlib/files/9310233/000009.csv)

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0]

Qlib version: 0.8.6
numpy==1.23.1
pandas==1.4.3
scipy==1.9.0
requests==2.28.1
[data.zip](https://github.com/microsoft/qlib/files/9310237/data.zip)

sacred==0.8.2
python-socketio==5.7.1
redis==4.3.4
python-redis-lock==3.7.0
schedule==1.1.0
cvxpy==1.2.1
hyperopt==0.1.2
fire==0.4.0
statsmodels==0.13.2
xlrd==2.0.1
plotly==5.9.0
matplotlib==3.5.2
tables==3.7.0
pyyaml==6.0
mlflow==1.27.0
tqdm==4.64.0
loguru==0.6.0
lightgbm==3.3.2
tornado==6.2
joblib==1.1.0
fire==0.4.0
ruamel.yaml==0.17.21
```

**Comment by jingedawang** [comment]
I also encountered the same error.

**Comment by jingedawang** [comment]
But I can't reproduce this error. Maybe due to some incomplete installation?

**Comment by Vincent4zzzz** [comment]
I also met the problem in different machine. I used the same way to reproduce the enviorment that can run qlib smoothly, but the bug still occured.
Qlib version: 0.8.6
Python version: 3.8.0
OS (Windows, Linux, MacOS): Linux
Commit number (optional, please provide it if you are using the dev version):

**Comment by Vincent4zzzz** [comment]
Also I cannot even locate this variable.

**Comment by liningbo** [comment]
the exception cause by the following code in ops.py in my case, which is in python 3.8 and qlib 0.8.6 and windows 10.
try:
    from ._libs.rolling import rolling_slope, rolling_rsquare, rolling_resi
    from ._libs.expanding import expanding_slope, expanding_rsquare, expanding_resi
except ImportError:
    print(
        "#### Do not import qlib package in the repository directory in case of importing qlib from . without compiling #####"
    )
    raise
except ValueError:
    print("!!!!!!!! A error occurs when importing operators implemented based on Cython.!!!!!!!!")
    print("!!!!!!!! They will be disabled. Please Upgrade your numpy to enable them     !!!!!!!!")
    # We catch this error because some platform can't upgrade there package (e.g. Kaggle)
    # https://www.kaggle.com/general/293387
    # https://www.kaggle.com/product-feedback/98562

**Comment by liningbo** [comment]
> the exception cause by the following code in ops.py in my case after debug, which is in python 3.8 and qlib 0.8.6 and windows 10 and vscode.
> 
> try: from ._libs.rolling import rolling_slope, rolling_rsquare, rolling_resi from ._libs.expanding import expanding_slope, expanding_rsquare, expanding_resi except ImportError: print( "#### Do not import qlib package in the repository directory in case of importing qlib from . without compiling #####" ) raise except ValueError: print("!!!!!!!! A error occurs when importing operators implemented based on Cython.!!!!!!!!") print("!!!!!!!! They will be disabled. Please Upgrade your numpy to enable them !!!!!!!!") # We catch this error because some platform can't upgrade there package (e.g. Kaggle) # https://www.kaggle.com/general/293387 # https://www.kaggle.com/product-feedback/98562

I solved the problem. I download vs studio 2022 community, and install from source useing 'python setup.py install' . copy the qlib directory in  build\lib.win-amd64-3.8 to site-packages. I think it is the rolling.cp38-win_amd64.pyd and expanding.cp38-win_amd64.pyd not suite for my machine ,so i compile them again in my machine, it is ok.

**Comment by pfcstyle** [comment]
I solved the problem. I removed my old virtual env and re-create a new virtual env and reinstall pylib by `pip install .`.
