### ISSUE TITLE
on qrun:"mlflow.exceptions.MlflowException: Param value .... had length 780, which exceeded length limit of 500 "

### ISSUE THREAD

**Issue by nkchem09** [microsoft/qlib#1317]
## 🐛 Bug Description

when I do the example:
qrun qrun benchmarks\GATs\workflow_config_gats_Alpha158.yaml

I got the error info:

(py38) D:\worksPool\works2021\adair2021\S92\P4\qlib-main\examples>qrun benchmarks\GATs\workflow_config_gats_Alpha158_full02.yaml
[7724:MainThread](2022-10-14 07:53:33,890) INFO - qlib.Initialization - [config.py:413] - default_conf: client.
[7724:MainThread](2022-10-14 07:53:33,890) INFO - qlib.workflow - [expm.py:31] - experiment manager uri is at file:D:\worksPool\works2021\adair2021\S92\P4\qlib-main\examples\mlruns
[7724:MainThread](2022-10-14 07:53:33,890) INFO - qlib.Initialization - [__init__.py:74] - qlib successfully initialized based on client settings.
[7724:MainThread](2022-10-14 07:53:33,890) INFO - qlib.Initialization - [__init__.py:76] - data_path={'__DEFAULT_FREQ': WindowsPath('C:/Users/adair2019/.qlib/qlib_data/cn_data')}
[7724:MainThread](2022-10-14 07:53:33,906) INFO - qlib.workflow - [expm.py:316] - <mlflow.tracking.client.MlflowClient object at 0x0000017B5D406F40>
[7724:MainThread](2022-10-14 07:53:33,906) INFO - qlib.workflow - [exp.py:260] - Experiment 3 starts running ...
[7724:MainThread](2022-10-14 07:53:34,124) INFO - qlib.workflow - [recorder.py:339] - Recorder 41d40d173e614811bad721127a3204b8 starts running under Experiment 3 ...
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
[7724:MainThread](2022-10-14 07:53:34,140) INFO - qlib.workflow - [recorder.py:372] - Fail to log the uncommitted code of $CWD when run `git diff`
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
[7724:MainThread](2022-10-14 07:53:34,158) INFO - qlib.workflow - [recorder.py:372] - Fail to log the uncommitted code of $CWD when run `git status`
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
[7724:MainThread](2022-10-14 07:53:34,164) INFO - qlib.workflow - [recorder.py:372] - Fail to log the uncommitted code of $CWD when run `git diff --cached`
Exception in thread Thread-1:
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\envs\py38\lib\site-packages\mlflow-1.29.0-py3.8.egg\mlflow\tracking\_tracking_service\client.py", line 301, in log_param
    self.store.log_param(run_id, param)
  File "d:\ProgramData\Anaconda3\envs\py38\lib\site-packages\mlflow-1.29.0-py3.8.egg\mlflow\store\tracking\file_store.py", line 887, in log_param
    _validate_param(param.key, param.value)
  File "d:\ProgramData\Anaconda3\envs\py38\lib\site-packages\mlflow-1.29.0-py3.8.egg\mlflow\utils\validation.py", line 148, in _validate_param
    _validate_length_limit("Param value", MAX_PARAM_VAL_LENGTH, value)
  File "d:\ProgramData\Anaconda3\envs\py38\lib\site-packages\mlflow-1.29.0-py3.8.egg\mlflow\utils\validation.py", line 269, in _validate_length_limit
    raise MlflowException(
mlflow.exceptions.MlflowException: Param value '[{'class': 'SignalRecord', 'module_path': 'qlib.workflow.record_temp', 'kwargs': {'model': '<MODEL>', 'dataset': '<DATASET>'}}, {'class': 'SigAnaRecord', 'module_path': 'qlib.workflow.record_temp', 'kwargs': {'ana_long_short': False, 'ann_scaler': 25' had length 780, which exceeded length limit of 500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\envs\py38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "d:\ProgramData\Anaconda3\envs\py38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ProgramData\Anaconda3\envs\py38\lib\site-packages\pyqlib-0.8.6.99-py3.8-win-amd64.egg\qlib\utils\paral.py", line 91, in run
    data()
  File "d:\ProgramData\Anaconda3\envs\py38\lib\site-packages\pyqlib-0.8.6.99-py3.8-win-amd64.egg\qlib\workflow\recorder.py", line 441, in log_params
    self.client.log_param(self.id, name, data)
  File "d:\ProgramData\Anaconda3\envs\py38\lib\site-packages\mlflow-1.29.0-py3.8.egg\mlflow\tracking\client.py", line 858, in log_param
    self._tracking_client.log_param(run_id, key, value)
  File "d:\ProgramData\Anaconda3\envs\py38\lib\site-packages\mlflow-1.29.0-py3.8.egg\mlflow\tracking\_tracking_service\client.py", line 305, in log_param
    raise MlflowException(msg, INVALID_PARAMETER_VALUE)
mlflow.exceptions.MlflowException: Param value '[{'class': 'SignalRecord', 'module_path': 'qlib.workflow.record_temp', 'kwargs': {'model': '<MODEL>', 'dataset': '<DATASET>'}}, {'class': 'SigAnaRecord', 'module_path': 'qlib.workflow.record_temp', 'kwargs': {'ana_long_short': False, 'ann_scaler': 25' had length 780, which exceeded length limit of 500

The cause of this error is typically due to repeated calls
to an individual run_id event logging.

Incorrect Example:
---------------------------------------
with mlflow.start_run():
    mlflow.log_param("depth", 3)
    mlflow.log_param("depth", 5)
---------------------------------------

Which will throw an MlflowException for overwriting a
logged parameter.

Correct Example:
---------------------------------------
with mlflow.start_run():
    with mlflow.start_run(nested=True):
        mlflow.log_param("depth", 3)
    with mlflow.start_run(nested=True):
        mlflow.log_param("depth", 5)
---------------------------------------

Which will create a new nested run for each individual
model and prevent parameter key collisions within the
tracking store.'
[7724:MainThread](2022-10-14 07:53:35,515) INFO - qlib.GATs - [pytorch_gats_ts.py:81] - GATs pytorch version...
[7724:MainThread](2022-10-14 07:53:35,562) INFO - qlib.GATs - [pytorch_gats_ts.py:100] - GATs parameters setting:
d_feat : 158
hidden_size : 64
num_layers : 2
dropout : 0.7
n_epochs : 200
lr : 0.0001
metric : loss
early_stop : 10
optimizer : adam
loss_type : mse
base_model : LSTM
model_path : None
visible_GPU : 0
use_GPU : True
seed : None
[7724:MainThread](2022-10-14 07:53:35,562) INFO - qlib.GATs - [pytorch_gats_ts.py:146] - model:
GATModel(
  (rnn): LSTM(158, 64, num_layers=2, batch_first=True, dropout=0.7)
  (transformation): Linear(in_features=64, out_features=64, bias=True)
  (fc): Linear(in_features=64, out_features=64, bias=True)
  (fc_out): Linear(in_features=64, out_features=1, bias=True)
  (leaky_relu): LeakyReLU(negative_slope=0.01)
  (softmax): Softmax(dim=1)
)

Then the program re-run again.
I am wondering how to fix it.
Thanks a lot.

## To Reproduce

1.
1.
1.

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:
 - 0.8.6.99'
 - Python version:
 - 3.8.5
 - OS (`Windows`, `Linux`, `MacOS`):
 - windows 10
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by Gila-6** [comment]
I had the same problem TT

**Comment by 0liu** [comment]
Same for all the example in `benchmarks/LightGBM`.

**Comment by qianyun210603** [comment]
This is because mlflow limits the length of params since 1.28.0.
While waiting the official qlib developers to find some way to accommodate this, downgrading mlflow to 1.27.0 can be a temp solution.

**Comment by nkchem09** [comment]
> This is because mlflow limits the length of params since 1.28.0. While waiting the official qlib developers to find some way to accommodate this, downgrading mlflow to 1.27.0 can be a temp solution.

Thank you for help. Wish you have a good day.
