### ISSUE TITLE
qlib/examples/workflow_by_code.py::: OSError: [WinError 1] 函数不正确。: 'Z:\\Temp\\tmpdsumgfzp'  // Can not Save model ~~

### ISSUE THREAD

**Issue by sundaymemo** [microsoft/qlib#1442]
Qlib ver:  v0.9.0
Python 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.31.1 -- An enhanced Interactive Python.

Restarting kernel...

runfile('E:/qlib/examples/workflow_by_code.py', wdir='E:/qlib/examples')
2023-02-21 15:02:57.885 | WARNING  | qlib.tests.data:qlib_data:150 - Data already exists: ~/.qlib/qlib_data/cn_data, the data download will be skipped
	If downloading is required: `exists_skip=False` or `change target_dir`
[5876:MainThread](2023-02-21 15:02:57,889) INFO - qlib.Initialization - [config.py:416] - default_conf: client.
[5876:MainThread](2023-02-21 15:02:57,896) INFO - qlib.Initialization - [__init__.py:74] - qlib successfully initialized based on client settings.
[5876:MainThread](2023-02-21 15:02:57,897) INFO - qlib.Initialization - [__init__.py:76] - data_path={'__DEFAULT_FREQ': WindowsPath('C:/Users/youjc/.qlib/qlib_data/cn_data')}
ModuleNotFoundError. CatBoostModel are skipped. (optional: maybe installing CatBoostModel can fix it.)
[5876:MainThread](2023-02-21 15:03:29,756) INFO - qlib.timer - [log.py:128] - Time cost: 29.809s | Loading data Done
[5876:MainThread](2023-02-21 15:03:30,968) INFO - qlib.timer - [log.py:128] - Time cost: 0.445s | DropnaLabel Done
E:\Anaconda3\lib\site-packages\qlib\data\dataset\processor.py:322: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols] = df[cols].groupby("datetime", group_keys=False).apply(self.zscore_func)
[5876:MainThread](2023-02-21 15:03:37,734) INFO - qlib.timer - [log.py:128] - Time cost: 6.765s | CSZScoreNorm Done
[5876:MainThread](2023-02-21 15:03:37,759) INFO - qlib.timer - [log.py:128] - Time cost: 8.002s | fit & process data Done
[5876:MainThread](2023-02-21 15:03:37,761) INFO - qlib.timer - [log.py:128] - Time cost: 37.815s | Init data Done
[5876:MainThread](2023-02-21 15:03:38,816) INFO - qlib.workflow - [exp.py:258] - Experiment 1 starts running ...
                           KMID      KLEN  ...   VSUMD60    LABEL0
datetime   instrument                      ...                    
2008-01-02 SH600000    0.010374  0.061129  ... -0.020675  0.042064
           SH600004    0.057280  0.059661  ... -0.029863  0.000000
           SH600006    0.012673  0.040323  ... -0.049861 -0.008830
           SH600007    0.066977  0.084186  ...  0.159104  0.007495
           SH600008    0.051163  0.082326  ...  0.060235 -0.015446

[5 rows x 159 columns]
[5876:MainThread](2023-02-21 15:03:39,132) INFO - qlib.workflow - [recorder.py:341] - Recorder ea7e0d76288f48fc897b3fda3a737195 starts running under Experiment 1 ...
Training until validation scores don't improve for 50 rounds
[20]	train's l2: 0.990585	valid's l2: 0.99431
[40]	train's l2: 0.986931	valid's l2: 0.993693
[60]	train's l2: 0.984352	valid's l2: 0.99349
[80]	train's l2: 0.982278	valid's l2: 0.993398
[100]	train's l2: 0.980459	valid's l2: 0.993321
[120]	train's l2: 0.978684	valid's l2: 0.993361
[140]	train's l2: 0.976979	valid's l2: 0.993392
Early stopping, best iteration is:
[100]	train's l2: 0.980459	valid's l2: 0.993321
[5876:MainThread](2023-02-21 15:03:55,966) INFO - qlib.timer - [log.py:128] - Time cost: 0.681s | waiting `async_log` Done
Traceback (most recent call last):

  File "E:\Anaconda3\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "e:\qlib\examples\workflow_by_code.py", line 74, in <module>
    R.save_objects(**{"params.pkl": model})

  File "E:\Anaconda3\lib\site-packages\qlib\workflow\__init__.py", line 521, in save_objects
    self.get_exp().get_recorder(start=True).save_objects(local_path, artifact_path, **kwargs)

  File "E:\Anaconda3\lib\site-packages\qlib\workflow\recorder.py", line 402, in save_objects
    temp_dir = Path(tempfile.mkdtemp()).resolve()

  File "E:\Anaconda3\lib\pathlib.py", line 1215, in resolve
    s = self._flavour.resolve(self, strict=strict)

  File "E:\Anaconda3\lib\pathlib.py", line 215, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))

OSError: [WinError 1] 函数不正确。: 'Z:\\Temp\\tmpdsumgfzp'

**Comment by Fivele-Li** [comment]
The error is likely caused by an issue with the temporary directory creation on your system.Here are a few steps you can try to resolve the issue:

Check if your temporary directory exists:
Ensure that the temporary directory 'Z:\Temp' exists. If it doesn't, create the directory or change the location of the temporary directory to an existing one.

Change the temporary directory:
It is possible that the temporary directory specified in your script or system is not correct or not accessible. You can try setting the TMP and TEMP environment variables to a different location before running your script.

For example, you can set the environment variables in Python like this:

```python
import os
os.environ['TMP'] = 'C:\\Temp'
os.environ['TEMP'] = 'C:\\Temp'
```
