### ISSUE TITLE
run "qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml" in a debug mode

### ISSUE THREAD

**Issue by jiaxings** [microsoft/qlib#170]
Hello, I try to understand the code structure of Qlib, I wonder if it could be run in a debug mode.
I tried the test_all_pipeline.py but failed with below infomation

Connected to pydev debugger (build 183.4284.139)
Launching unittests with arguments python -m unittest C:/Users/Laputa/PycharmProjects/qlib/tests/test_all_pipeline.py in C:\Users\Laputa\PycharmProjects\qlib\tests

#### Do not import qlib package in the repository directory in case of importing qlib from . without compiling #####
Error
Traceback (most recent call last):
  File "C:\Users\Laputa\Anaconda3\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\Laputa\Anaconda3\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\Laputa\Anaconda3\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_all_pipeline
Traceback (most recent call last):
  File "C:\Users\Laputa\Anaconda3\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\Laputa\PycharmProjects\qlib\tests\test_all_pipeline.py", line 15, in <module>
    from qlib.contrib.model.gbdt import LGBModel
  File "C:\Users\Laputa\PycharmProjects\qlib\qlib\contrib\model\gbdt.py", line 8, in <module>
    from ...model.base import ModelFT
  File "C:\Users\Laputa\PycharmProjects\qlib\qlib\model\__init__.py", line 6, in <module>
    from .base import Model
  File "C:\Users\Laputa\PycharmProjects\qlib\qlib\model\base.py", line 5, in <module>
    from ..data.dataset import Dataset
  File "C:\Users\Laputa\PycharmProjects\qlib\qlib\data\__init__.py", line 8, in <module>
    from .data import (
  File "C:\Users\Laputa\PycharmProjects\qlib\qlib\data\data.py", line 21, in <module>
    from .cache import H
  File "C:\Users\Laputa\PycharmProjects\qlib\qlib\data\cache.py", line 36, in <module>
    from .ops import *
  File "C:\Users\Laputa\PycharmProjects\qlib\qlib\data\ops.py", line 18, in <module>
    from ._libs.rolling import rolling_slope, rolling_rsquare, rolling_resi
ModuleNotFoundError: No module named 'qlib.data._libs.rolling'

**Comment by you-n-g** [comment]
@jiaxings 
Please check the info in the output.
![image](https://user-images.githubusercontent.com/465606/103458129-1cb80600-4d40-11eb-8e7d-c65c0ea5ef13.png)

**Comment by you-n-g** [comment]
@Derek-Wds 
I think we can add some docs about how to run qlib wih pdb.
`python -m pdb workflow/cli.py`
