### ISSUE TITLE
Online client sample codes failed

### ISSUE THREAD

**Issue by tracoco** [microsoft/qlib#184]
## 🐛 Bug Description

Following https://github.com/microsoft/qlib-server#using-qlib-in-online-mode, the codes failed at
`ins = D.list_instruments(D.instrumetns("all"), as_list=True)`
with error:
`BadNamespaceError                         Traceback (most recent call last)`

## To Reproduce

1. One key deploy using docker-compose
2. Run the sample codes

```python
~/git/qlib/examples/test.py in 
     81 
     82 qlib.init(**ONLINE_CONFIG)
---> 83 ins = D.list_instruments(D.instruments("all"), as_list=True)
     84 
     85 

~/.local/lib/python3.8/site-packages/qlib/data/data.py in list_instruments(self, instruments, start_time, end_time, freq, as_list)
    948 
    949     def list_instruments(self, instruments, start_time=None, end_time=None, freq="day", as_list=False):
--> 950         return Inst.list_instruments(instruments, start_time, end_time, freq, as_list)
    951 
    952     def features(

~/.local/lib/python3.8/site-packages/qlib/data/data.py in list_instruments(self, instruments, start_time, end_time, freq, as_list)
    808             return instrument
    809 
--> 810         self.conn.send_request(
    811             request_type="instrument",
    812             request_content={

~/.local/lib/python3.8/site-packages/qlib/data/client.py in send_request(self, request_type, request_content, msg_queue, msg_proc_func)
     99         self.sio.on(request_type + "_response", request_callback)
    100         self.logger.debug("try sending")
--> 101         self.sio.emit(request_type + "_request", request_content)
    102         self.sio.wait()

~/.local/lib/python3.8/site-packages/socketio/client.py in emit(self, event, data, namespace, callback)
    326         namespace = namespace or '/'
    327         if namespace not in self.namespaces:
--> 328             raise exceptions.BadNamespaceError(
    329                 namespace + ' is not a connected namespace.')
    330         self.logger.info('Emitting event "%s" [%s]', event, namespace)

BadNamespaceError: / is not a connected namespace.
```
## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

Qlib version: 0.6.1

Python version: ['3.8.5 (default, Jul 28 2020, 12:59:40) ', '[GCC 9.3.0]']

linux_distribution: N/A
system: Linux
machine: x86_64
platform: Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29
version: #1 SMP Wed Feb 19 06:37:35 UTC 2020

## Additional Notes

sockerio version is latest 5.0.4 which is not what qlib recommends. But when I manually installed socketio 3.1.2, it thrown other probem which can't connect server.

**Comment by zhupr** [comment]
@tracoco Hi,
What is the configuration of client and server?

**Comment by tracoco** [comment]
Hi,
The server is deployed using docker compose with default config except for IP is a remote IP. The client is just the sample code in attached webpage with IP used the server.



---Original---

**Comment by tracoco** [comment]
Hi,
Is there update for this?

**Comment by zhupr** [comment]
@tracoco Hi,
- Can the `ip` and `port` of `qlib-server` be accessed normally? Use `telnet` to try it: `telnet <qlib-server ip addr> 9710`
- Check if `qlib-server` is started normally: `sudo docker-compose -f docker_support/docker-compose.yaml logs -f`

**Comment by tracoco** [comment]
Yes. the server started and can be telnet properly. From call stack it seems emit thrown the exception after connecting to server.

        self.connect_server()
        self.logger.debug("connected")
        # The pickle is for passing some parameters with special type(such as
        # pd.Timestamp)
        request_content = {"head": head_info, "body": pickle.dumps(request_content)}
        self.sio.on(request_type + "_response", request_callback)
        self.logger.debug("try sending")
        self.sio.emit(request_type + "_request", request_content)
`

**Comment by tracoco** [comment]
Just to clarify, above exception is from socketio v5.
Did two more tests with socketio v3:
1. Tested qlib client on deployed server with new virtualenv with just pyqlib installed. It passed
2. Created a new virtualenv under WSL2 env and pip install pyqlib, this will install socketio v3, the error now is:
`
[13409:MainThread](2021-02-05 11:40:03,180) ERROR - qlib.workflow - [utils.py:35] - An exception has been raised[TypeError: send() got an unexpected keyword argument 'binary'].
  File "test_online.py", line 28, in <module>
    ins = D.list_instruments(D.instruments("all"), as_list=True)
  File "/home/lee/python/qlib/lib/python3.8/site-packages/qlib/data/data.py", line 942, in list_instruments
    return Inst.list_instruments(instruments, start_time, end_time, freq, as_list)
  File "/home/lee/python/qlib/lib/python3.8/site-packages/qlib/data/data.py", line 802, in list_instruments
    self.conn.send_request(
  File "/home/lee/python/qlib/lib/python3.8/site-packages/qlib/data/client.py", line 101, in send_request
    self.sio.emit(request_type + "_request", request_content)
  File "/home/lee/python/qlib/lib/python3.8/site-packages/socketio/client.py", line 263, in emit
    self._send_packet(packet.Packet(packet.EVENT, namespace=namespace,
  File "/home/lee/python/qlib/lib/python3.8/site-packages/socketio/client.py", line 339, in _send_packet
    self.eio.send(ep, binary=binary)
TypeError: send() got an unexpected keyword argument 'binary'
^C^Z
`

**Comment by zhupr** [comment]
Your problem seems to be caused by *xxx-socketio*, refer to: https://github.com/miguelgrinberg/python-socketio/issues/582
Try it like this:
- find packages that contain *socketio* : `pip list|grep socketio`, then delete them. 
- reinstall *python-socketio*: `pip install python-socketio`

**Comment by tracoco** [comment]
As described in first report, that trick will install socketio v5, and get error of "BadNamespaceError: / is not a connected namespace.".

Before using that trick, the error is "TypeError: send() got an unexpected keyword argument 'binary'".

I actually deleted whole virtualenv from WSL and copied working virtualenv from the server, and got same errors. Do you have WSL2 ubuntu to try?

**Comment by zhupr** [comment]
I did not use WSL2, after that I installed and tested

**Comment by tracoco** [comment]
Sorry, do you mean you installed WSL2 and tested? If so, I may reinstall my WSL2.

FYI, I just now tested on ubuntu live USB 20.04 and works.

**Comment by tracoco** [comment]
Tested on a new WSL2 env and it works, although not sure what's wrong with old env.

**Comment by tracoco** [comment]
Not sure what's your testing env, and what's socketIO expected behavior. But I guess emit thrown the exception as the connection is not setup yet. In qlib/data/client.py, please check whether
`self.sio.emit(request_type + "_request", request_content)` 
should be changed to something like:
`        self.sio.on(
            "connect",
            lambda: self.sio.emit(request_type + "_request", request_content),
        )
`
