### ISSUE TITLE
qrun call python3 default rather than python2

### ISSUE THREAD

**Issue by jinfagang** [microsoft/qlib#304]
```
Traceback (most recent call last):
  File "/usr/local/bin/qrun", line 11, in <module>
    load_entry_point('pyqlib', 'console_scripts', 'qrun')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/media/fagangjin/samsung/source/ai/quant/qlib/qlib/workflow/__init__.py", line 5, in <module>
    from .expm import MLflowExpManager
  File "/media/fagangjin/samsung/source/ai/quant/qlib/qlib/workflow/expm.py", line 4, in <module>
    import mlflow
  File "/usr/local/lib/python3.6/dist-packages/mlflow-1.14.1-py3.6.egg/mlflow/__init__.py", line 52, in <module>
    import mlflow.fastai as fastai  # noqa: E402
  File "/usr/local/lib/python3.6/dist-packages/mlflow-1.14.1-py3.6.egg/mlflow/fastai.py", line 19, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.6/dist-packages/pandas-1.2.3-py3.6-linux-x86_64.egg/pandas/__init__.py", line 51, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.6/dist-packages/pandas-1.2.3-py3.6-linux-x86_64.egg/pandas/core/api.py", line 6, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/usr/local/lib/python3.6/dist-packages/pandas-1.2.3-py3.6-linux-x86_64.egg/pandas/core/dtypes/dtypes.py", line 27, in <module>
    from pandas.core.dtypes.base import ExtensionDtype, register_extension_dtype
  File "/usr/local/lib/python3.6/dist-packages/pandas-1.2.3-py3.6-linux-x86_64.egg/pandas/core/dtypes/base.py", line 12, in <module>
    from pandas.core.dtypes.generic import ABCDataFrame, ABCIndexClass, ABCSeries
  File "/usr/local/lib/python3.6/dist-packages/pandas-1.2.3-py3.6-linux-x86_64.egg/pandas/core/dtypes/generic.py", line 2
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined


```

python2 have syntax errors.

**Comment by you-n-g** [comment]
@jinfagang   Python 2 is deprecated by Python Community and is not supported by Qlib.

**Comment by jinfagang** [comment]
@you-n-g  I mean currently it calls python xxx which will call python2 default in most linux distributions such as ubuntu 16.04.

**Comment by Derek-Wds** [comment]
Some of the Qlib's functionalities depends on packages such as `numpy` and `pandas`, which stop supporting python2 for a long time. If you really want to use Qlib with python2, you can modify related codes by yourself. Thanks.

**Comment by you-n-g** [comment]
@jinfagang  I think the easiest solution is using anaconda to manage your python environment

**Comment by jinfagang** [comment]
@Derek-Wds  You missed my question. I mean on ubuntu 16.04, defaults python will call python2. I don't want it. Wrap python inside executable is not siutable...

**Comment by Derek-Wds** [comment]
@jinfagang OH, I see. I would recommend you to use Anaconda to manage your python versions as well. It is better to find a way to avoid running python2 by default on your system.
