### ISSUE TITLE
yahoo collector returns error

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#356]
command:
`python .qlib/scripts/data_collector/yahoo/collector.py download_data --source_dir .csv-yahoo --region US --start 2021-03-18 --end 2021-03-19 --delay 0.1 --interval 1d`
Bug report:

```
Traceback (most recent call last):
  File ".qlib/scripts/data_collector/yahoo/collector.py", line 642, in <module>
    fire.Fire(Run)
  File "xxxxxxxxxxxxxxxx/.venv/lib/python3.7/site-packages/fire-0.3.1-py3.7.egg/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "xxxxxxxxxxxxxxxx/.venv/lib/python3.7/site-packages/fire-0.3.1-py3.7.egg/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "xxxxxxxxxxxxxxxx/.venv/lib/python3.7/site-packages/fire-0.3.1-py3.7.egg/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File ".qlib/scripts/data_collector/yahoo/collector.py", line 622, in download_data
    super(Run, self).download_data(max_collector_count, delay, start, end, interval, check_data_length, limit_nums)
  File "xxxxxxxxxxxxxxxx/.qlib/scripts/data_collector/base.py", line 404, in download_data
    limit_nums=limit_nums,
TypeError: Can't instantiate abstract class YahooCollectorUS1d with abstract methods get_instrument_list

```

**Comment by you-n-g** [comment]
Merged.
Thanks  @zhupr  so much!

@angry     Is your problem solved?

**Comment by 2young-2simple-sometimes-naive** [comment]
> Merged.
> Thanks @zhupr so much!
> 
> @Angry Is your problem solved?

Yes it's working now.
