### ISSUE TITLE
bug in data_collector/us_index

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#375]
input:
`python .qlib/scripts/data_collector/us_index/collector.py --index_name NASDAQ100 --qlib_dir qlib_data/us_data --method parse_instruments`
error:
```
2021-03-26 06:29:59.508 | INFO     | data_collector.index:parse_instruments:184 - start parse nasdaq100 companies.....
2021-03-26 06:29:59.508 | INFO     | collector:get_history_companies:152 - start get history companies......
2021-03-26 06:29:59.508 | INFO     | data_collector.utils:get_calendar_list:61 - get calendar list: US_ALL......
2021-03-26 06:30:00.282 | INFO     | data_collector.utils:get_calendar_list:97 - end of get calendar list: US_ALL.
100%|████████████████████████████████████████████████████████████████| 4589/4589 [03:05<00:00, 24.72it/s]
2021-03-26 06:33:06.111 | WARNING  | collector:get_history_companies:167 - get error: [Timestamp('2008-11-17 00:00:00'), Timestamp('2008-11-18 00:00:00'), Timestamp('2020-06-10 00:00:00'), Timestamp('2020-06-11 00:00:00'), Timestamp('2020-06-12 00:00:00')]
2021-03-26 06:33:06.111 | INFO     | collector:get_history_companies:168 - total 4589, error 5
2021-03-26 06:33:06.111 | INFO     | collector:get_history_companies:169 - end of get history companies.
2021-03-26 06:33:08.677 | INFO     | data_collector.index:get_changes_with_history_companies:147 - parse changes from history companies......
100%|████████████████████████████████████████████████████████████████| 4584/4584 [06:07<00:00, 12.49it/s]
2021-03-26 06:39:16.001 | INFO     | data_collector.index:get_changes_with_history_companies:174 - end of parse changes from history companies.
2021-03-26 06:39:16.062 | INFO     | collector:get_new_companies:103 - get new companies NASDAQ100 ......
Traceback (most recent call last):
  File ".qlib/scripts/data_collector/us_index/collector.py", line 282, in <module>
    fire.Fire(get_instruments)
  File "xxxxxxxxxxxxxxxxxxxxxxxxxx/.venv-yfinance/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "xxxxxxxxxxxxxxxxxxxxxxxxxx/.venv-yfinance/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "xxxxxxxxxxxxxxxxxxxxxxxxxx/.venv-yfinance/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File ".qlib/scripts/data_collector/us_index/collector.py", line 278, in get_instruments
    getattr(obj, method)()
  File "xxxxxxxxxxxxxxxxxxxxxxxxxx/.qlib/scripts/data_collector/index.py", line 187, in parse_instruments
    new_df = self.get_new_companies().copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by zhupr** [comment]
@2young-2simple-sometimes-naive Hi,
The bug is fixed：https://github.com/microsoft/qlib/pull/379
