### ISSUE TITLE
Filter Pipe gives error:  KeyError: 'func' 

### ISSUE THREAD

**Issue by jmrichardson** [microsoft/qlib#608]
## 🐛 Bug Description

I am getting the following error when attempting to use a filter:

```
[2760:MainThread](2021-09-17 13:04:01,554) INFO - qlib.Initialization - [config.py:350] - default_conf: client.
[2760:MainThread](2021-09-17 13:04:03,559) WARNING - qlib.Initialization - [config.py:375] - redis connection failed(host=127.0.0.1 port=6379), DiskDatasetCache will not be used!
[2760:MainThread](2021-09-17 13:04:04,268) INFO - qlib.Initialization - [__init__.py:58] - qlib successfully initialized based on client settings.
[2760:MainThread](2021-09-17 13:04:04,269) INFO - qlib.Initialization - [__init__.py:60] - data_path={'__DEFAULT_FREQ': WindowsPath('D:/Projects/aim/data/daily/qlib')}
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Projects/aim/workflow.py", line 76, in <module>
    dataset = init_instance_by_config(task["dataset"])
  File "D:\Anaconda3\envs\aim\lib\site-packages\pyqlib-0.7.1-py3.8-win-amd64.egg\qlib\utils\__init__.py", line 277, in init_instance_by_config
    return klass(**cls_kwargs, **kwargs)
  File "D:\Anaconda3\envs\aim\lib\site-packages\pyqlib-0.7.1-py3.8-win-amd64.egg\qlib\data\dataset\__init__.py", line 115, in __init__
    self.handler: DataHandler = init_instance_by_config(handler, accept_types=DataHandler)
  File "D:\Anaconda3\envs\aim\lib\site-packages\pyqlib-0.7.1-py3.8-win-amd64.egg\qlib\utils\__init__.py", line 277, in init_instance_by_config
    return klass(**cls_kwargs, **kwargs)
  File "D:\Projects\aim\aim\qlib\handler.py", line 168, in __init__
    super().__init__(
  File "D:\Anaconda3\envs\aim\lib\site-packages\pyqlib-0.7.1-py3.8-win-amd64.egg\qlib\data\dataset\handler.py", line 380, in __init__
    super().__init__(instruments, start_time, end_time, data_loader, **kwargs)
  File "D:\Anaconda3\envs\aim\lib\site-packages\pyqlib-0.7.1-py3.8-win-amd64.egg\qlib\data\dataset\handler.py", line 92, in __init__
    self.data_loader = init_instance_by_config(
  File "D:\Anaconda3\envs\aim\lib\site-packages\pyqlib-0.7.1-py3.8-win-amd64.egg\qlib\utils\__init__.py", line 277, in init_instance_by_config
    return klass(**cls_kwargs, **kwargs)
  File "D:\Anaconda3\envs\aim\lib\site-packages\pyqlib-0.7.1-py3.8-win-amd64.egg\qlib\data\dataset\loader.py", line 178, in __init__
    filter_pipe = [
  File "D:\Anaconda3\envs\aim\lib\site-packages\pyqlib-0.7.1-py3.8-win-amd64.egg\qlib\data\dataset\loader.py", line 179, in <listcomp>
    init_instance_by_config(fp, None if "module_path" in fp else filter_module, accept_types=BaseDFilter)
  File "D:\Anaconda3\envs\aim\lib\site-packages\pyqlib-0.7.1-py3.8-win-amd64.egg\qlib\utils\__init__.py", line 276, in init_instance_by_config
    klass, cls_kwargs = get_callable_kwargs(config, default_module=default_module)
  File "D:\Anaconda3\envs\aim\lib\site-packages\pyqlib-0.7.1-py3.8-win-amd64.egg\qlib\utils\__init__.py", line 216, in get_callable_kwargs
    _callable = getattr(module, config["class" if "class" in config else "func"])
KeyError: 'func'
python-BaseException
```

I believe it is looking for a class definition.  I tried setting a class and module_path but didn't work.  thanks for any help

## To Reproduce

Using the following code with filter_pipe:

```
import qlib
# from qlib.contrib.data.handler import Alpha158
# from aim.qlib.handler import Alpha158
# from qlib.contrib.model.gbdt import LGBModel
from qlib.utils import exists_qlib_data, init_instance_by_config
from aim.qlib.ops import Day
from qlib.data.filter import ExpressionDFilter


filter = {
    # 'class': 'ExpressionDFilter',
    # "module_path": "qlib.data.filter",
    'filter_type': 'ExpressionDFilter',
    'rule_expression': "$close > 0",
    'filter_start_time': None,
    'filter_end_time': None,
    'keep': False,
}


data_handler_config = {
    "start_time": "2008-01-01",
    "end_time": "2020-08-01",
    "fit_start_time": "2008-01-01",
    "fit_end_time": "2014-12-31",
    "instruments": 'test',
    "filter_pipe": [filter],
}


task = {
    "model": {
        "class": "LGBModel",
        "module_path": "qlib.contrib.model.gbdt",
        "kwargs": {
            "loss": "mse",
            "colsample_bytree": 0.8879,
            "learning_rate": 0.0421,
            "subsample": 0.8789,
            "lambda_l1": 205.6999,
            "lambda_l2": 580.9768,
            "max_depth": 8,
            "num_leaves": 210,
            "num_threads": 20,
        },
    },
    "dataset": {
        "class": "DatasetH",
        "module_path": "qlib.data.dataset",
        "kwargs": {
            "handler": {
                "class": "Alpha158",
                # "module_path": "qlib.contrib.data.handler",
                "module_path": "aim.qlib.handler",
                "kwargs": data_handler_config,
            },
            "segments": {
                "train": ("2008-01-01", "2014-12-31"),
                "valid": ("2015-01-01", "2016-12-31"),
                "test": ("2017-01-01", "2020-08-01"),
            },
        },
    },
}

# custom_ops = {"custom_ops": [Day]}

if __name__ == "__main__":

    # qlib.init(provider_uri="data/daily/qlib", dataset_cache="SimpleDatasetCache", local_cache_path='data/daily/qlib/cache')
    # qlib.init(provider_uri="data/daily/qlib", dataset_cache="SimpleDatasetCache", expression_cache=None, **custom_ops)
    # qlib.init(provider_uri="data/daily/qlib", expression_cache=None, **custom_ops)
    qlib.init(provider_uri="data/daily/qlib")

    # model initiaiton
    model = init_instance_by_config(task["model"])
    dataset = init_instance_by_config(task["dataset"])

    model.fit(dataset)  # fits on train and valid data segments
    model.predict(dataset)  # predicts test data
```

1.  Executing the above code

## Expected Behavior

Did not execute and failed with error

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

```
Qlib version: 0.7.1
numpy==1.20.0
pandas==1.3.2
scipy==1.7.1
requests==2.26.0
sacred==0.8.2
python-socketio==5.4.0
redis==3.5.3
python-redis-lock==3.7.0
schedule==1.1.0
cvxpy==1.0.21
hyperopt==0.1.1
fire==0.4.0
statsmodels==0.12.2
xlrd==2.0.1
plotly==4.12.0
matplotlib==3.1.3
tables==3.6.1
pyyaml==5.4.1
mlflow==1.20.2
tqdm==4.62.2
loguru==0.5.3
lightgbm==3.2.1
tornado==6.1
joblib==1.0.1
fire==0.4.0
ruamel.yaml==0.17.16
```

**Comment by zhupr** [comment]
@jmrichardson Hi,
`bug` fixed in this PR: https://github.com/microsoft/qlib/pull/611
