### ISSUE TITLE
par.generate() out of bounds error

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#638]
## 🐛 Bug Description

```
[33585:MainThread](2021-10-08 07:03:55,693) ERROR - qlib.workflow - [utils.py:38] - An exception has been raised[IndexError: index 8001 is out of bounds for axis 0 with size 8001].
  File "./workflow.py", line 117, in <module>
    par.generate()
  File "/home/xxxxxxxx/.venv/lib/python3.8/site-packages/pyqlib-0.7.2.99-py3.8-linux-x86_64.egg/qlib/workflow/record_temp.py", line 372, in generate
    portfolio_metric_dict, indicator_dict = normal_backtest(
  File "/home/xxxxxxxx/.venv/lib/python3.8/site-packages/pyqlib-0.7.2.99-py3.8-linux-x86_64.egg/qlib/backtest/__init__.py", line 251, in backtest
    portfolio_metrics, indicator = backtest_loop(start_time, end_time, trade_strategy, trade_executor)
  File "/home/xxxxxxxx/.venv/lib/python3.8/site-packages/pyqlib-0.7.2.99-py3.8-linux-x86_64.egg/qlib/backtest/backtest.py", line 28, in backtest_loop
    for _decision in collect_data_loop(start_time, end_time, trade_strategy, trade_executor, return_value):
  File "/home/xxxxxxxx/.venv/lib/python3.8/site-packages/pyqlib-0.7.2.99-py3.8-linux-x86_64.egg/qlib/backtest/backtest.py", line 65, in collect_data_loop
    _trade_decision: BaseTradeDecision = trade_strategy.generate_trade_decision(_execute_result)
  File "/home/xxxxxxxx/.venv/lib/python3.8/site-packages/pyqlib-0.7.2.99-py3.8-linux-x86_64.egg/qlib/contrib/strategy/model_strategy.py", line 88, in generate_trade_decision
    trade_start_time, trade_end_time = self.trade_calendar.get_step_time(trade_step)
  File "/home/xxxxxxxx/.venv/lib/python3.8/site-packages/pyqlib-0.7.2.99-py3.8-linux-x86_64.egg/qlib/backtest/utils.py", line 117, in get_step_time
    return self._calendar[calendar_index], epsilon_change(self._calendar[calendar_index + 1])
```

## To Reproduce

```
port_analysis_config = {
    "strategy": {
        "class": "TopkDropoutStrategy",
        "module_path": "qlib.contrib.strategy.model_strategy",
        "kwargs": {
            "model": model1,
            "dataset": dataset,
            "topk": 30,
            "n_drop": 5,
        },
    },
    "backtest": {
        "start_time": valid_start,
        "end_time": test_end,
        "account": 100000,
        "benchmark": benchmark,
        "exchange_kwargs":{
            "deal_price": "open",
            "open_cost": 0.0005,
            "close_cost": 0.0015,
            "min_cost": 5,
        }
    },
}
par = PortAnaRecord(recorder, port_analysis_config, "day")
par.generate()
```

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version: git e99224e
 - Python version: 3.8
 - OS (`Windows`, `Linux`, `MacOS`): CentOS
 - Commit number (optional, please provide it if you are using the dev version): e99224e

**Comment by you-n-g** [comment]
@2young-2simple-sometimes-naive 
The backtest framework is refactored in the latest version. Some interfaces are changed.

You can run the latest example here https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.py#L76

**Comment by 2young-2simple-sometimes-naive** [comment]
Hi. I am not using the default testing data. I am downloading the us daily data from yahoo. `par.generate()` used to work for the data I am using. From the error log it looks like the index for daily calendar is broken with the new implemented `par.generate()` .

Also I have tried to download the test data and it returned `requests.exceptions.HTTPError`.

**Comment by 2young-2simple-sometimes-naive** [comment]
```
(master ✓) fin python .qlib/scripts/get_data.py qlib_data .
Traceback (most recent call last):
  File ".qlib/scripts/get_data.py", line 9, in <module>
    fire.Fire(GetData)
  File "/home/xxxxxxxx/.venv/lib/python3.8/site-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/xxxxxxxx/.venv/lib/python3.8/site-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/xxxxxxxx/.venv/lib/python3.8/site-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/xxxxxxxx/.venv/lib/python3.8/site-packages/pyqlib-0.7.2.99-py3.8-linux-x86_64.egg/qlib/tests/data.py", line 164, in qlib_data
    self._download_data(file_name.lower(), target_dir, delete_old, dataset_version=version)
  File "/home/xxxxxxxx/.venv/lib/python3.8/site-packages/pyqlib-0.7.2.99-py3.8-linux-x86_64.egg/qlib/tests/data.py", line 51, in _download_data
    raise requests.exceptions.HTTPError()
requests.exceptions.HTTPError
```

**Comment by you-n-g** [comment]
Will it raise the same error if you use the recommended command?
https://github.com/microsoft/qlib#data-preparation

What  URL are you trying to access you are trying to access data? 
https://github.com/microsoft/qlib/blob/main/qlib/tests/data.py#L49

**Comment by igor17400** [comment]
@2young-2simple-sometimes-naive How did you manage to solve this bug? 
I'm facing the same problem 

`IndexError: index 3112 is out of bounds for axis 0 with size 3112`

**Comment by dexter31** [comment]
Can reproduce. Pity it has to happen after 12 hours of training :)

**Comment by BenjiKCF** [comment]
same problem, Tried with "Get with module" and "Get from source". Both shows IndexError: index XXX is out of bounds for axis 0 with size YYY.
