### ISSUE TITLE
download data costs a lot of time 

### ISSUE THREAD

**Issue by aiot-tech** [microsoft/qlib#750]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.
When downloading  and updating data using the command line:
```
python scripts/data_collector/yahoo/collector.py update_data_to_bin --qlib_data_1d_dir ~/.qlib/qlib_data/cn_data/ --trading_date 2021-06-15 --end_date 2021-12-10
```
it costs a lot of time ! Any plans to accelerate it?~~~

**Comment by zhupr** [comment]
@aiot-tech Hi,
add "delay" or "max_workers": `--delay 0.1 --max_workers 10`
 If the number of concurrency is more or the delay is less, it is possible that the acquired data is incomplete, set these two parameters according to the specific situation

**Comment by aiot-tech** [comment]
```
2021-12-16 22:37:44.151 | INFO     | collector:get_instrument_list:196 - get HS stock symbols......
2021-12-16 22:37:57.195 | INFO     | collector:get_instrument_list:198 - get 4298 symbols.
2021-12-16 22:37:57.419 | INFO     | data_collector.base:collector_data:204 - start collector data......
2021-12-16 22:37:57.419 | INFO     | data_collector.base:collector_data:209 - getting data: 1
  0%|          | 0/4298 [00:00<?, ?it/s]Traceback (most recent call last):
  File "scripts/data_collector/yahoo/collector.py", line 1124, in <module>
    fire.Fire(Run)
  File "D:\ProgramData\Miniconda3\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\ProgramData\Miniconda3\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\ProgramData\Miniconda3\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "scripts/data_collector/yahoo/collector.py", line 1091, in update_data_to_bin
    self.download_data(delay=delay, start=trading_date, end=end_date, check_data_length=check_data_length)
  File "scripts/data_collector/yahoo/collector.py", line 903, in download_data
    super(Run, self).download_data(
  File "C:\Users\lalala\qlib\scripts\data_collector\base.py", line 392, in download_data
    _class(
  File "C:\Users\lalala\qlib\scripts\data_collector\yahoo\collector.py", line 185, in collector_data
    super(YahooCollector, self).collector_data()
  File "C:\Users\lalala\qlib\scripts\data_collector\base.py", line 210, in collector_data
    instrument_list = self._collector(instrument_list)
  File "C:\Users\lalala\qlib\scripts\data_collector\base.py", line 190, in _collector
    res = Parallel(n_jobs=self.max_workers)(
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\parallel.py", line 968, in __call__
    n_jobs = self._initialize_backend()
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\parallel.py", line 735, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 191, in register
    self._send('REGISTER', name, rtype)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 204, in _send
    msg = '{0}:{1}:{2}\n'.format(cmd, name, rtype).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xb7' in position 20: ordinal not in range(128)
  0%|          | 0/4298 [00:00<?, ?it/s]
```
a few questions are encountered...

**Comment by zhupr** [comment]
> ```
> 2021-12-16 22:37:44.151 | INFO     | collector:get_instrument_list:196 - get HS stock symbols......
> 2021-12-16 22:37:57.195 | INFO     | collector:get_instrument_list:198 - get 4298 symbols.
> 2021-12-16 22:37:57.419 | INFO     | data_collector.base:collector_data:204 - start collector data......
> 2021-12-16 22:37:57.419 | INFO     | data_collector.base:collector_data:209 - getting data: 1
>   0%|          | 0/4298 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "scripts/data_collector/yahoo/collector.py", line 1124, in <module>
>     fire.Fire(Run)
>   File "D:\ProgramData\Miniconda3\lib\site-packages\fire\core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "D:\ProgramData\Miniconda3\lib\site-packages\fire\core.py", line 466, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "D:\ProgramData\Miniconda3\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "scripts/data_collector/yahoo/collector.py", line 1091, in update_data_to_bin
>     self.download_data(delay=delay, start=trading_date, end=end_date, check_data_length=check_data_length)
>   File "scripts/data_collector/yahoo/collector.py", line 903, in download_data
>     super(Run, self).download_data(
>   File "C:\Users\lalala\qlib\scripts\data_collector\base.py", line 392, in download_data
>     _class(
>   File "C:\Users\lalala\qlib\scripts\data_collector\yahoo\collector.py", line 185, in collector_data
>     super(YahooCollector, self).collector_data()
>   File "C:\Users\lalala\qlib\scripts\data_collector\base.py", line 210, in collector_data
>     instrument_list = self._collector(instrument_list)
>   File "C:\Users\lalala\qlib\scripts\data_collector\base.py", line 190, in _collector
>     res = Parallel(n_jobs=self.max_workers)(
>   File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\parallel.py", line 968, in __call__
>     n_jobs = self._initialize_backend()
>   File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\parallel.py", line 735, in _initialize_backend
>     n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
>   File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
>     self._workers = get_memmapping_executor(
>   File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
>     return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
>   File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
>     manager = TemporaryResourcesManager(temp_folder)
>   File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
>     self.set_current_context(context_id)
>   File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
>     self.register_new_context(context_id)
>   File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
>     self.register_folder_finalizer(new_folder_path, context_id)
>   File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
>     resource_tracker.register(pool_subfolder, "folder")
>   File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 191, in register
>     self._send('REGISTER', name, rtype)
>   File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 204, in _send
>     msg = '{0}:{1}:{2}\n'.format(cmd, name, rtype).encode('ascii')
> UnicodeEncodeError: 'ascii' codec can't encode character '\xb7' in position 20: ordinal not in range(128)
>   0%|          | 0/4298 [00:00<?, ?it/s]
> ```
> 
> a few questions are encountered...when running the comlind line below :
> 
> ```shell
> python scripts/data_collector/yahoo/collector.py update_data_to_bin --qlib_data_1d_dir ~/.qlib/qlib_data/cn_data1/ --trading_date 2021-06-15 --end_date 2021-12-10 --max_workers 8
> ```
Whether there is Chinese in the surrogate path, or output name at `D:\ProgramData\Miniconda3\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py, line 204`, look at the value of `name`

**Comment by aiot-tech** [comment]
The path does not contain any Chinese character. And I move the qlib folder from c: to d: drive,but the same problem occurred again.
```2021-12-16 23:12:55.131 | INFO     | collector:get_instrument_list:196 - get HS stock symbols......
2021-12-16 23:13:23.985 | INFO     | collector:get_instrument_list:198 - get 4298 symbols.
2021-12-16 23:13:24.085 | INFO     | data_collector.base:collector_data:204 - start collector data......
2021-12-16 23:13:24.085 | INFO     | data_collector.base:collector_data:209 - getting data: 1
  0%|          | 0/4298 [00:00<?, ?it/s]Traceback (most recent call last):
  File "scripts/data_collector/yahoo/collector.py", line 1124, in <module>
    fire.Fire(Run)
  File "D:\ProgramData\Miniconda3\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\ProgramData\Miniconda3\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\ProgramData\Miniconda3\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "scripts/data_collector/yahoo/collector.py", line 1091, in update_data_to_bin
    self.download_data(delay=delay, start=trading_date, end=end_date, check_data_length=check_data_length)
  File "scripts/data_collector/yahoo/collector.py", line 903, in download_data
    super(Run, self).download_data(
  File "D:\qlib_backtest\qlib\scripts\data_collector\base.py", line 392, in download_data
    _class(
  File "D:\qlib_backtest\qlib\scripts\data_collector\yahoo\collector.py", line 185, in collector_data
    super(YahooCollector, self).collector_data()
  File "D:\qlib_backtest\qlib\scripts\data_collector\base.py", line 210, in collector_data
    instrument_list = self._collector(instrument_list)
  File "D:\qlib_backtest\qlib\scripts\data_collector\base.py", line 190, in _collector
    res = Parallel(n_jobs=self.max_workers)(
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\parallel.py", line 968, in __call__
    n_jobs = self._initialize_backend()
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\parallel.py", line 735, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 191, in register
    self._send('REGISTER', name, rtype)
  File "D:\ProgramData\Miniconda3\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 204, in _send
    msg = '{0}:{1}:{2}\n'.format(cmd, name, rtype).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xb7' in position 20: ordinal not in range(128)
  0%|          | 0/4298 [00:00<?, ?it/s]


```

**Comment by zhupr** [comment]
> D:\ProgramData\Miniconda3\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py

Open this file(`D:\ProgramData\Miniconda3\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py`) and add `print(cmd, name, rtype)` before line 204 to see the result:

```python
    def _send(self, cmd, name, rtype):
        print(cmd, name, rtype)
        msg = '{0}:{1}:{2}\n'.format(cmd, name, rtype).encode('ascii')
        if len(name) > 512:
            # posix guarantees that writes to a pipe of less than PIPE_BUF
            # bytes are atomic, and that PIPE_BUF >= 512
            raise ValueError('name too long')
        nbytes = os.write(self._fd, msg)
        assert nbytes == len(msg)
```

**Comment by aiot-tech** [comment]
It works!Thanks a lot!

**Comment by aiot-tech** [comment]
Hi,pr@zhupr! when I use the script below to download data:
```
python scripts/data_collector/yahoo/collector.py update_data_to_bin --qlib_data_1d_dir ~/.qlib/qlib_data/cn_data/ --trading_date 2021-06-15 --end_date 2021-12-10 --max_workers 8
```
some wornings were occurred
```
2021-12-20 16:26:44.822 | WARNING  | data_collector.utils:wrapper:429 - _get_simple: 3 :get data error: 000065.sz--2021-06-15 00:00:00+08:00--2021-12-10 00:00:00+08:00
2021-12-20 16:26:44.822 | WARNING  | data_collector.utils:wrapper:429 - _get_simple: 3 :get data error: 000066.sz--2021-06-15 00:00:00+08:00--2021-12-10 00:00:00+08:00
```
What should I do to check if the result ``` ~/.qlib/qlib_data/cn_data/ ``` is correct

**Comment by zhupr** [comment]
@aiot-tech Hi,
This may be a network problem or the stock is "delisted", so the data is not available

**Comment by aiot-tech** [comment]
ok~,I will try it again

**Comment by temph2020** [comment]
> It works!Thanks a lot!

How do you resolve it?
