### ISSUE TITLE
Loading data by Alpha158 handler with my own data get ValueError: operands could not be broadcast together with shapes (1854,) (0,)

### ISSUE THREAD

**Issue by polaris-gogh** [microsoft/qlib#785]
## ❓ Questions and Help

I got my own data by tushare and dumped the data  to bin files. Then I followed the example of loading data by Alpha158 handler classs and got the ValueError: operands could not be broadcast together with shapes (1854,) (0,).

Here is my code:
market = "HS300"
data_handler_config = {
    "start_time": "2014-05-21",
    "end_time": "2021-12-24",
    "fit_start_time": "2014-05-21",
    "fit_end_time": "2019-01-03",
    "instruments": market,
}
h = Alpha158(**data_handler_config)
print(h.get_cols())

Here is the error message:
Traceback (most recent call last):

  File "E:\python\qlib_research\my_demo.py", line 250, in <module>
    dataset = init_instance_by_config(task["dataset"])

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\utils\__init__.py", line 305, in init_instance_by_config
    return klass(**cls_kwargs, **try_kwargs, **kwargs)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\__init__.py", line 115, in __init__
    self.handler: DataHandler = init_instance_by_config(handler, accept_types=DataHandler)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\utils\__init__.py", line 305, in init_instance_by_config
    return klass(**cls_kwargs, **try_kwargs, **kwargs)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\contrib\data\handler.py", line 167, in __init__
    super().__init__(

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\handler.py", line 389, in __init__
    super().__init__(instruments, start_time, end_time, data_loader, **kwargs)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\handler.py", line 105, in __init__
    self.setup_data()

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\handler.py", line 525, in setup_data
    super().setup_data(**kwargs)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\handler.py", line 149, in setup_data
    self._data = lazy_sort_index(self.data_loader.load(self.instruments, self.start_time, self.end_time))

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\loader.py", line 134, in load
    {

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\loader.py", line 135, in <dictcomp>
    grp: self.load_group_df(instruments, exprs, names, start_time, end_time, grp)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\loader.py", line 210, in load_group_df
    df = D.features(

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\data.py", line 1026, in features
    return DatasetD.dataset(instruments, fields, start_time, end_time, freq, inst_processors=inst_processors)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\data.py", line 761, in dataset
    data = self.dataset_processor(

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\data.py", line 534, in dataset_processor
    ParallelExt(n_jobs=workers, backend=C.joblib_backend, maxtasksperchild=C.maxtasksperchild)(task_l),

  File "C:\Users\polaris\anaconda3\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()

  File "C:\Users\polaris\anaconda3\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))

  File "C:\Users\polaris\anaconda3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value

ValueError: operands could not be broadcast together with shapes (1854,) (0,) 

I need help, plz.

**Comment by Wangwuyi123** [comment]
We paid attention to your problem and tried to reproduce your problem, but we do not have the same data as you, can you provide your data or a script to get the data.

**Comment by polaris-gogh** [comment]
> We paid attention to your problem and tried to reproduce your problem, but we do not have the same data as you, can you provide your data or a script to get the data.

Please download my data: https://1drv.ms/u/s!AvwFBl2Ou9AmqGC17DxYyajs-0FG?e=5V9b1Z

**Comment by Wangwuyi123** [comment]
I have received your data, please provide your specific order

**Comment by polaris-gogh** [comment]
> I have received your data, please provide your specific order

Sorry for my carelessness. At first I run the following codes:
`market = "HS300"`
`benchmark = "SH000300"`
`data_handler_config = {
    "start_time": "2014-05-21",
    "end_time": "2021-12-24",
    "fit_start_time": "2014-05-21",
    "fit_end_time": "2019-01-03",
    "instruments": market,
}`
`task = {
    "model": {
        "class": "LGBModel",
        "module_path": "qlib.contrib.model.gbdt",
        "kwargs": {
            "loss": "mse",
            "colsample_bytree": 0.8879,
            "learning_rate": 0.0421,
            "subsample": 0.8789,
            "lambda_l1": 205.6999,
            "lambda_l2": 580.9768,
            "max_depth": 8,
            "num_leaves": 210,
            "num_threads": 20,
        },
    },
    "dataset": {
        "class": "DatasetH",
        "module_path": "qlib.data.dataset",
        "kwargs": {
            "handler": {
                "class": "Alpha158",
                "module_path": "qlib.contrib.data.handler",
                "kwargs": data_handler_config,
            },
            "segments": {
                "train": ("2014-05-21", "2019-01-03"),
                "valid": ("2019-01-04", "2020-12-31"),
                "test": ("2021-01-01", "2021-12-24"),
            },
        },
    },
}`
 `model = init_instance_by_config(task["model"])` 
`dataset = init_instance_by_config(task["dataset"])`
And I got the ValueError: operands could not be broadcast together with shapes (1854,) (0,).  Sorry I pasted the first error message details. The code run stop at Alpha158 Handler, so I read the Qlib Documentation. Then I annotated all unnecessary code and copy the example code from "https://qlib.readthedocs.io/en/latest/component/data.html?highlight=Alpha158#example", and I got the ValueError again. 

Here is my copy code:
`import qlib` 
`from qlib.config import REG_CN`
`from qlib.contrib.data.handler import Alpha158`
`market = "HS300"`
`data_handler_config = {
    "start_time": "2014-05-21",
    "end_time": "2021-12-24",
    "fit_start_time": "2014-05-21",
    "fit_end_time": "2019-01-03",
    "instruments": market,
}`
`if __name__ == "__main__":`
`qlib.init(provider_uri='./my_data/qlib_data', region=REG_CN)`
`h = Alpha158(**data_handler_config)`
`print(h.get_cols())`


The error message showed :
Traceback (most recent call last):

  File "E:\python\qlib_research\my_demo.py", line 259, in <module>
    h = Alpha158(**data_handler_config)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\contrib\data\handler.py", line 167, in __init__
    super().__init__(

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\handler.py", line 389, in __init__
    super().__init__(instruments, start_time, end_time, data_loader, **kwargs)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\handler.py", line 105, in __init__
    self.setup_data()

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\handler.py", line 525, in setup_data
    super().setup_data(**kwargs)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\handler.py", line 149, in setup_data
    self._data = lazy_sort_index(self.data_loader.load(self.instruments, self.start_time, self.end_time))

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\loader.py", line 134, in load
    {

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\loader.py", line 135, in <dictcomp>
    grp: self.load_group_df(instruments, exprs, names, start_time, end_time, grp)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\dataset\loader.py", line 210, in load_group_df
    df = D.features(

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\data.py", line 1026, in features
    return DatasetD.dataset(instruments, fields, start_time, end_time, freq, inst_processors=inst_processors)

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\data.py", line 761, in dataset
    data = self.dataset_processor(

  File "C:\Users\polaris\anaconda3\lib\site-packages\qlib\data\data.py", line 534, in dataset_processor
    ParallelExt(n_jobs=workers, backend=C.joblib_backend, maxtasksperchild=C.maxtasksperchild)(task_l),

  File "C:\Users\polaris\anaconda3\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()

  File "C:\Users\polaris\anaconda3\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))

  File "C:\Users\polaris\anaconda3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value

ValueError: operands could not be broadcast together with shapes (1863,) (0,) 


I also considered whether the market variables was wrong, so I changed instruments to 'all'. `market = "all"` But I still got the error.

**Comment by polaris-gogh** [comment]
> I have received your data, please provide your specific order

I've solved the problem.  The reason is that I used 'vol' as a column name of csv file to dump. It works when I changed the column name from 'vol' to 'volume' and dumped csv files again. Thank you anyway.

**Comment by j123425** [comment]
Hi, I met the same error when using my own data and Alpha158 handler. May I know what's the format of your csv file?

**Comment by polaris-gogh** [comment]
give me your e-mail adress



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2025年4月23日(星期三) 下午2:57
To: ***@***.***&gt;; 
Cc: " ***@***.***&gt;; "State ***@***.***&gt;; 
Subject: Re: [microsoft/qlib] Loading data by Alpha158 handler with my own data get ValueError: operands could not be broadcast together with shapes (1854,) (0,) (Issue #785)












   
Hi, I met the same error when using my own data and Alpha158 handler. May I know what's the format of your csv file?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
  j123425 left a comment (microsoft/qlib#785)
 
Hi, I met the same error when using my own data and Alpha158 handler. May I know what's the format of your csv file?
