### ISSUE TITLE
qlib demo 运行问题

### ISSUE THREAD

**Issue by bjtuql** [microsoft/qlib#861]

**Comment by bjtuql** [comment]
我从pip和source两种方式安装qlib，source方式显示了一个error，error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/，我把这个问题解决后，使用qlib.__version__可以正常显示qlib的版本，但是当我用命令运行demo（环境是win11 + anaconda），报如下错误：

$ qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml
E:\anaconda\envs\demo\lib\site-packages\arctic\_util.py:6: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
Traceback (most recent call last):
  File "E:\anaconda\envs\demo\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\anaconda\envs\demo\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\anaconda\envs\demo\Scripts\qrun.exe\__main__.py", line 4, in <module>
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\workflow\cli.py", line 12, in <module>
    from qlib.model.trainer import task_train
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\model\__init__.py", line 6, in <module>
    from .base import Model
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\model\base.py", line 6, in <module>
    from ..data.dataset import Dataset
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\__init__.py", line 8, in <module>
    from .data import (
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\data.py", line 20, in <module>
    from arctic import Arctic
  File "E:\anaconda\envs\demo\lib\site-packages\arctic\__init__.py", line 6, in <module>
    from .store._pandas_ndarray_store import PandasDataFrameStore, PandasSeriesStore, PandasPanelStore
  File "E:\anaconda\envs\demo\lib\site-packages\arctic\store\_pandas_ndarray_store.py", line 6, in <module>
    from pandas import DataFrame, Series, Panel
ImportError: cannot import name 'Panel' from 'pandas' (E:\anaconda\envs\demo\lib\site-packages\pandas\__init__.py)
(demo)
这是我安装qlib失败的问题还是demo 运行问题？

**Comment by you-n-g** [comment]
I think this is caused by the conflict between your newer version of Pandas  and the requirements of Arctic https://github.com/man-group/arctic/blob/master/setup.py#L82

But pip should have solved this issue.
Can you describe  steps to reproduce the error from a **clean Python environment**?

**Comment by bjtuql** [comment]
> 
The steps are as below, and I will create a new python environment to check it.

1. create a clean conda environment, python 3.7(I see the demo is python 3.7)

2. Then, I first install qlib with **pip**, it succeed, but when I run the demo it has error:
$ qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml
[20360:MainThread](2022-01-18 15:19:33,128) INFO - qlib.Initialization - [config.py:384] - default_conf: client.
[20360:MainThread](2022-01-18 15:19:33,138) INFO - qlib.Initialization - [__init__.py:57] - qlib successfully initialized based on client settings.
[20360:MainThread](2022-01-18 15:19:33,138) INFO - qlib.Initialization - [__init__.py:59] - data_path={'__DEFAULT_FREQ': WindowsPath('C:/Users/mujou/.qlib/qlib_data/cn_data
')}
[20360:MainThread](2022-01-18 15:19:33,138) INFO - qlib.workflow - [expm.py:282] - No tracking URI is provided. Use the default tracking URI.
[20360:MainThread](2022-01-18 15:19:33,138) INFO - qlib.workflow - [expm.py:318] - <mlflow.tracking.client.MlflowClient object at 0x000002116262ABC8>
[20360:MainThread](2022-01-18 15:19:33,178) WARNING - qlib.workflow - [expm.py:200] - No valid experiment found. Create a new experiment with name workflow.
[20360:MainThread](2022-01-18 15:19:33,188) INFO - qlib.workflow - [exp.py:249] - Experiment 1 starts running ...
[20360:MainThread](2022-01-18 15:19:33,429) INFO - qlib.workflow - [recorder.py:290] - Recorder 9cf5243040d4459faa05c44f6cd2961d starts running under Experiment 1 ...
Please install necessary libs for CatBoostModel.
Please install necessary libs for XGBModel, such as xgboost.
Please install necessary libs for PyTorch models.
[20360:MainThread](2022-01-18 15:19:33,689) INFO - qlib.timer - [log.py:113] - Time cost: 0.000s | waiting `async_log` Done
[20360:MainThread](2022-01-18 15:19:33,689) ERROR - qlib.workflow - [utils.py:38] - An exception has been raised[ValueError: can't find a freq from [] that can resample to
day!].
  File "E:\anaconda\envs\demo\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\anaconda\envs\demo\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\anaconda\envs\demo\Scripts\qrun.exe\__main__.py", line 7, in <module>
    sys.exit(run())
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\workflow\cli.py", line 62, in run
    fire.Fire(workflow)
  File "E:\anaconda\envs\demo\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "E:\anaconda\envs\demo\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "E:\anaconda\envs\demo\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\workflow\cli.py", line 56, in workflow
    recorder = task_train(config.get("task"), experiment_name=experiment_name)
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\model\trainer.py", line 166, in task_train
    _exe_task(task_config)
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\model\trainer.py", line 42, in _exe_task
    dataset: Dataset = init_instance_by_config(task_config["dataset"])
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\utils\__init__.py", line 305, in init_instance_by_config
    return klass(**cls_kwargs, **try_kwargs, **kwargs)
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\dataset\__init__.py", line 115, in __init__
    self.handler: DataHandler = init_instance_by_config(handler, accept_types=DataHandler)
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\utils\__init__.py", line 305, in init_instance_by_config
    return klass(**cls_kwargs, **try_kwargs, **kwargs)
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\contrib\data\handler.py", line 174, in __init__
    process_type=process_type,
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\dataset\handler.py", line 389, in __init__
    super().__init__(instruments, start_time, end_time, data_loader, **kwargs)
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\dataset\handler.py", line 105, in __init__
    self.setup_data()
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\dataset\handler.py", line 525, in setup_data
    super().setup_data(**kwargs)
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\dataset\handler.py", line 149, in setup_data
    self._data = lazy_sort_index(self.data_loader.load(self.instruments, self.start_time, self.end_time))
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\dataset\loader.py", line 136, in load
    for grp, (exprs, names) in self.fields.items()
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\dataset\loader.py", line 136, in <dictcomp>
    for grp, (exprs, names) in self.fields.items()
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\dataset\loader.py", line 211, in load_group_df
    instruments, exprs, start_time, end_time, freq=freq, inst_processors=self.inst_processor.get(gp_name, [])
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\data.py", line 1023, in features
    instruments, fields, start_time, end_time, freq, disk_cache, inst_processors=inst_processors
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\cache.py", line 408, in dataset
    instruments, fields, start_time, end_time, freq, disk_cache, inst_processors=inst_processors
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\cache.py", line 743, in _dataset
    inst_processors=inst_processors,
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\cache.py", line 900, in gen_dataset_cache
    _calendar = Cal.calendar(freq=freq)
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\data.py", line 100, in calendar
    _calendar, _calendar_index = self._get_calendar(freq, future)
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\data.py", line 181, in _get_calendar
    _calendar = np.array(self.load_calendar(freq, future))
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\data.py", line 620, in load_calendar
    backend_obj = self.backend_obj(freq=freq, future=future).data
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\storage\file_storage.py", line 108, in data
    self.check()
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\storage\file_storage.py", line 59, in check
    if not self.uri.exists():
  File "E:\anaconda\envs\demo\lib\site-packages\qlib\data\storage\file_storage.py", line 102, in uri
    raise ValueError(f"can't find a freq from {self.support_freq} that can resample to {self.freq}!")
**ValueError: can't find a freq from [] that can resample to day!**
(demo)
I wan to see which line cause the error, but every line is from the externel lib.
3.  So I think my installation failed before, then I install from **the source way** in the docs, it has the error:
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/, after I install visual-cpp-build-tools, I solve it, and I can import qlib and print its version
4. Then I run the demo, get the error presented before.

**Comment by you-n-g** [comment]
Did you follow the steps [here ](https://github.com/microsoft/qlib#data-preparation) to download data?

**Comment by bjtuql** [comment]
I'm sorry I didn't prepare the data, but I think the demo video add this step could be better
