### ISSUE TITLE
ValueError: need at most 63 handles, got a sequence of length 64

### ISSUE THREAD

**Issue by xiangqingcs** [microsoft/qlib#926]
## 🐛 Bug Description

I use qlib to run the class of Alpha158, the error message is following
```
(qlib_080a1) D:\project>python run_alpha158_factor.py
[21200:MainThread](2022-02-23 13:44:03,147) INFO - qlib.Initialization - [config.py:386] - default_conf: client.
[21200:MainThread](2022-02-23 13:44:04,163) WARNING - qlib.Initialization - [config.py:411] - redis connection failed(host=127.0.0.1 port=6379), DiskExpressionCache and DiskDatasetCache will not be used!
[21200:MainThread](2022-02-23 13:44:05,320) INFO - qlib.Initialization - [__init__.py:56] - qlib successfully initialized based on client settings.
[21200:MainThread](2022-02-23 13:44:05,335) INFO - qlib.Initialization - [__init__.py:58] - data_path={'__DEFAULT_FREQ': WindowsPath('D:/factor_extract/20220222_qlib')}
199 199
Exception in thread Thread-1:
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\envs\qlib_080a1\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "d:\ProgramData\Anaconda3\envs\qlib_080a1\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ProgramData\Anaconda3\envs\qlib_080a1\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "d:\ProgramData\Anaconda3\envs\qlib_080a1\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "d:\ProgramData\Anaconda3\envs\qlib_080a1\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "d:\ProgramData\Anaconda3\envs\qlib_080a1\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 64
```

the script of run_alpha158_factor.py is following.
```
provider_uri = r"D:/factor_extract/20220222_qlib"
qlib.init(provider_uri=provider_uri)
h = Alpha158(**data_handler_config)

# get all the columns of the data
print(h.get_cols())

# fetch all the labels
print(h.fetch(col_set="label"))

# fetch all the features
print(h.fetch(col_set="feature"))
```

Operating System Information：Windows Server 2016 Standard
CPU Information: Intel(R) Xeon(R) Gold 51228 CPU 2.30GHz  64 core 
Qlib version:   pyqlib 0.7.2.99
python version: 3.8
other reference： https://github.com/psf/black/issues/564

How do I limit my CPU cores by parameter in my python script?

**Comment by xiangqingcs** [comment]
This parameter modify is following.
```
NUM_USABLE_CPU = max(32, 1)
```

This method is invalid when i run the class of 'Alpha360',  but the error is not appear when i run the class of 'Alpha158'.  The error message is following.
```
[33532:MainThread](2022-03-07 13:14:39,773) INFO - qlib.Initialization - [config.py:388] - default_conf: client.
[33532:MainThread](2022-03-07 13:14:40,867) INFO - qlib.Initialization - [__init__.py:56] - qlib successfully initialized based on client settings.
[33532:MainThread](2022-03-07 13:14:40,868) INFO - qlib.Initialization - [__init__.py:58] - data_path={'__DEFAULT_FREQ': WindowsPath('D:/factor_extract/20220305_qlib')}
D:\ProgramData\Anaconda3\envs\qlib_080a1\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\utils\__init__.py:757: FutureWarning: MultiIndex.is_lexsorted is deprecated as a public function, users should use MultiIndex.is_monotonic_increasing instead.
  if idx.is_monotonic_increasing and not (isinstance(idx, pd.MultiIndex) and not idx.is_lexsorted()):
[33532:MainThread](2022-03-07 13:24:13,821) INFO - qlib.timer - [log.py:113] - Time cost: 572.950s | Loading data Done
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\qlib_080a1\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "D:\ProgramData\Anaconda3\envs\qlib_080a1\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 65
```

**Comment by SunsetWolf** [comment]
I guess there is a reason for using qlib version 0.7.2.99, but I sincerely suggest you try the latest version of qlib and maybe your issue can be solved.
