### ISSUE TITLE
Unable to download demo data

### ISSUE THREAD

**Issue by jeremytanjianle** [microsoft/qlib#983]
## Unable to download demo data

Unable to reproduce demo, at the data download step. 
By running the following command
```
python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/cn_data --region cn
```
The following error is encountered. 
```
2022-03-16 11:35:04.229 | WARNING  | qlib.tests.data:_download_data:57 - The data for the example is collected from Yahoo Finance. Please be aware that the quality of the data might not be perfect. (You can refer to the original data source: https://finance.yahoo.com/lookup.)
2022-03-16 11:35:04.234 | INFO     | qlib.tests.data:_download_data:59 - qlib_data_cn_1d_latest.zip downloading......
 48%|██████████████████████████████▌                                 | 103411712/216676710 [08:12<08:59, 210087.25it/s]
2022-03-16 11:43:16.472 | WARNING  | qlib.tests.data:_unzip:82 - will delete the old qlib data directory(features, instruments, calendars, features_cache, dataset_cache): C:\Users\limpe\.qlib\qlib_data\cn_data
2022-03-16 11:43:16.483 | INFO     | qlib.tests.data:_unzip:85 - C:\Users\limpe\.qlib\qlib_data\cn_data\20220316113503_qlib_data_cn_1d_latest.zip unzipping......
Traceback (most recent call last):
  File "scripts/get_data.py", line 9, in <module>
    fire.Fire(GetData)
  File "C:\Users\limpe\anaconda3\envs\qlib\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\limpe\anaconda3\envs\qlib\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "C:\Users\limpe\anaconda3\envs\qlib\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\limpe\anaconda3\envs\qlib\lib\site-packages\qlib\tests\data.py", line 166, in qlib_data
    self._download_data(file_name.lower(), target_dir, delete_old, dataset_version=version)
  File "C:\Users\limpe\anaconda3\envs\qlib\lib\site-packages\qlib\tests\data.py", line 66, in _download_data
    self._unzip(target_path, target_dir, delete_old)
  File "C:\Users\limpe\anaconda3\envs\qlib\lib\site-packages\qlib\tests\data.py", line 86, in _unzip
    with zipfile.ZipFile(str(file_path.resolve()), "r") as zp:
  File "C:\Users\limpe\anaconda3\envs\qlib\lib\zipfile.py", line 1225, in __init__
    self._RealGetContents()
  File "C:\Users\limpe\anaconda3\envs\qlib\lib\zipfile.py", line 1292, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by jeremytanjianle** [comment]
Solved by changing directory to `~/.qlib` and removing the `qlib_data` folder.
